nodeLinker: node-modules

npmAuditRegistry: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.18.0.cjs

npmPreapprovedPackages:
  - '@emnapi/*'
  - '@napi-rs/*'
  - '@oxlint/*'
  - '@oxfmt/*'
  - '@oxc-node/*'
  - emnapi
  - oxfmt
  - oxlint
