/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function plus100(input: number): number
export declare function hi(input: number): number
export declare function continuouslyRetryFunction(lambdaFunctionArn: string): Promise<string>
