/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function continuouslyRetryFunction(lambdaFunctionArn: string): Promise<string>
export declare function createInventoryTable(): Promise<void>
export declare function createCrashTable(): Promise<void>
export declare function toggleCrashTable(): Promise<void>
